package dev.javatofde.starter.flow;

public enum ReasonCode {
    MATCHED,
    INVOICE_ID_NOT_FOUND,
    AMBIGUOUS_INVOICE_ID,
    INVOICE_NOT_FOUND,
    PURCHASE_ORDER_MISSING,
    DUPLICATE_INVOICE,
    DOCUMENT_INCOMPLETE,
    PURCHASE_ORDER_INACTIVE,
    VENDOR_MISMATCH,
    CURRENCY_MISMATCH,
    AMOUNT_MISMATCH,
    MODEL_REVIEW_REQUIRED,
    MODEL_TIMEOUT,
    MODEL_INVALID_RESPONSE,
    MODEL_UNAVAILABLE
}
